sudo: false
dist: trusty

jobs:
  include:
    - stage: test
      script: "Running tests"
    - stage: build docker image
      script:
      - docker build -t ap/ap0001 .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker tag ap/ap0001 $DOCKER_USERNAME/ap0001
      - docker push $DOCKER_USERNAME/ap0001
    - stage: deploy
      script: skip
    