###
AWSTemplateFormatVersion: 2010-09-09
Description: AP0001 Job definitions 
###
###---Resources:JobDefinition---
###
Resources:
  AP0001:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: AP0001
      ContainerProperties:
        Image: 282921537141.dkr.ecr.ap-northeast-1.amazonaws.com/ap/ap0001:latest
        Vcpus: 1
        Memory: 1024
        Command: []
        Environment: []
        Ulimits: []
      RetryStrategy:
        Attempts: 1

#========CloudWatch Rules Schedule========#
  Cron: 
    Type: AWS::Events::Rule
    Properties: 
      Description: AP0001-Cron
      ScheduleExpression: cron(0/1 * * * ? *)
      State: "ENABLED"
      Targets: 
        - Id: AP0001-TriggerBatchAPJob
          Arn: arn:aws:lambda:ap-northeast-1:282921537141:function:TriggerBatchAPJob
          Input: "{\"jobDefinition\": \"AP0001\", \"jobQueue\": \"APJobQueue\"}"

  PermissionForTriggerBatchAPJob: 
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: TriggerBatchAPJob
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt Cron.Arn

#========Outputs========#
Outputs:
  AP0001Id:
    Description: AP0001 JobDefinition
    Value: !Ref AP0001
  CronId:
    Description: AP0001 CloudWatch Rules Schedule
    Value: !Ref Cron
  PermissionId: 
    Description: AP0001 CloudWatch TriggerBatchAPJob Permission
    Value: !Ref PermissionForTriggerBatchAPJob