###
AWSTemplateFormatVersion: 2010-09-09
Description: AP0001 Job definitions 
###
###---Resources:JobDefinition---
###
Resources:
  AP0001:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: AP0001
      ContainerProperties:
        Image: 282921537141.dkr.ecr.ap-northeast-1.amazonaws.com/ap/ap0001:latest
        Vcpus: 1
        Memory: 1024
        Command: []
        Environment: []
        Ulimits: []
      RetryStrategy:
        Attempts: 1

#========Outputs========#
Outputs:
  AP0001Id:
    Description: Id of AP0001 JobDefinition
    Value: !Ref AP0001