###
AWSTemplateFormatVersion: 2010-09-09
Description: AP Job definitions 

###
###---Parameters---
###
Parameters:
  APName:
    Type: String
    Description: AP Job Definition Name
  Queue:
    Type: String
    Description: AP Job Queue Name

###
###---Resources:JobDefinition---
###
Resources:
  APJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Ref APName
      ContainerProperties:
        Image: 282921537141.dkr.ecr.ap-northeast-1.amazonaws.com/ap/ap0001:latest
        Vcpus: 1
        Memory: 1024
        Command: []
        Environment: []
        Ulimits: []
      RetryStrategy:
        Attempts: 1

  #========CloudWatch Rules Schedule========#
  Cron: 
    Type: AWS::Events::Rule
    Properties: 
      Description: !Sub "${APName}-Cron"
      ScheduleExpression: cron(0/1 * * * ? *)
      State: "ENABLED"
      Targets: 
        - Id: !Sub "${APName}-TriggerBatchAPJob"
          Arn: arn:aws:lambda:ap-northeast-1:282921537141:function:TriggerBatchAPJob
          Input: !Sub "{\"jobDefinition\": \"${APName}\", \"jobQueue\": \"${Queue}\"}"

  PermissionForTriggerBatchAPJob: 
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: TriggerBatchAPJob
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt Cron.Arn

#========Outputs========#
Outputs:
  APJobDefinition:
    Description: AP Job Definition
    Value: !Ref APJobDefinition
  Cron:
    Description: AP CloudWatch Rules Schedule
    Value: !Ref Cron
  Permission: 
    Description: AP CloudWatch TriggerBatchAPJob Permission
    Value: !Ref PermissionForTriggerBatchAPJob