AWSTemplateFormatVersion: 2010-09-09
Description: Build AP AWS Batch Environment
 
#========VPC========#
Resources:
# Create VPC
  APVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/20
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "AP" ,"VPC" ] ]
        
# Create Public RouteTable
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref APVPC
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "AP" ,"PublicRoute" ] ]

# Create Public Subnet A
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref APVPC
      CidrBlock: 192.168.0.0/24
      MapPublicIpOnLaunch: 'true'
      AvailabilityZone: "ap-northeast-1a"
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "AP" ,"PublicSubnetA" ] ]
  PubSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

# Create Public Subnet C
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref APVPC
      CidrBlock: 192.168.1.0/24
      MapPublicIpOnLaunch: 'true'
      AvailabilityZone: "ap-northeast-1c"
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "AP" ,"PublicSubnetC" ] ]
  PubSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

# Create InternetGateway
  APInternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "AP" ,"InternetGateway" ] ]
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref APVPC
      InternetGatewayId: !Ref APInternetGateway

# Route for InternetGateway or VPNGateway
  APRoute:
    Type: AWS::EC2::Route
    DependsOn: APInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref APInternetGateway

# Security Groups for AP Batch Compute Environment
  APSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref APVPC
      GroupDescription: AP SecurityGroup
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

# S3 Bucket for AP Batch Compute Environment
  APS3Bucket:
    Type: AWS::S3::Bucket

#=======IAM========#
# Create ecsInstanceRole
  APECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
                - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

# Set InstanceProfile
  APECSInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref APECSInstanceRole
 
# Create AWSBatchServiceRole
  APBatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"  
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batch.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

# Create APAmazonEC2SpotFleetTaggingRole
  APAmazonEC2SpotFleetTaggingRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

###
### ---ComputeEnvironment---
###

# Create APComputeEnvironment
  # APComputeEnvironment:
  #   Type: "AWS::Batch::ComputeEnvironment"
  #   Properties:
  #     Type: MANAGED
  #     ServiceRole: !Ref APBatchServiceRole
  #     ComputeEnvironmentName: APComputeEnvironment
  #     ComputeResources:
  #       Ec2KeyPair: aws-ap
  #       MaxvCpus: 128
  #       MinvCpus: 2
  #       DesiredvCpus: 2
  #       SecurityGroupIds:
  #         - !Ref APSecurityGroup
  #       Type: EC2
  #       Subnets:
  #         - !Ref PublicSubnetA
  #         - !Ref PublicSubnetC
  #       InstanceRole: !Ref APECSInstanceProfile
  #       InstanceTypes:
  #         - c4.large
  #         - c4.xlarge
  #       Tags: {"Name": "AP Batch Compute Environment"}
  #     State: ENABLED

# Create SPOTAPComputeEnvironment
  SPOTAPComputeEnvironment:
    Type: "AWS::Batch::ComputeEnvironment"
    Properties:
      Type: MANAGED
      ServiceRole: !Ref APBatchServiceRole
      ComputeEnvironmentName: SPOTAPComputeEnvironment201709j
      ComputeResources:
        ImageId: ami-bb5f13dd
        Ec2KeyPair: aws-ap
        MaxvCpus: 128
        MinvCpus: 4
        DesiredvCpus: 4
        SecurityGroupIds:
          - !Ref APSecurityGroup
        Type: SPOT
        BidPercentage: 100
        SpotIamFleetRole: !Ref APAmazonEC2SpotFleetTaggingRole
        Subnets:
          - !Ref PublicSubnetA
          - !Ref PublicSubnetC
        InstanceRole: !Ref APECSInstanceProfile
        InstanceTypes:
          - m3.medium
        Tags: {"Name": "AP SPOT Batch Compute Environment"}
      State: ENABLED

###---Resources:JobQueue---
  APJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref SPOTAPComputeEnvironment
        # - Order: 2
        #   ComputeEnvironment: !Ref APComputeEnvironment
      State: ENABLED
      Priority: 500
      JobQueueName: APJobQueue

#========Outputs========#
Outputs:
  # APComputeEnvironment:
  #   Description: Id of APComputeEnvironment
  #   Value: !Ref APComputeEnvironment
  SPOTAPComputeEnvironment:
    Description: Id of SPOTAPComputeEnvironment
    Value: !Ref SPOTAPComputeEnvironment
  APJobQueue:
    Description: Id of APJobQueue
    Value: !Ref APJobQueue
  APS3Bucket:
    Description: Id of APS3Bucket
    Value: !GetAtt APS3Bucket.Arn
    Export:
      Name: APS3Bucket
